apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: API
  description: The Petstore API
spec:
  type: openapi
  lifecycle: production
  owner: petstore@example.com
  definition:
    $text: https://github.com/RapidX-Developer-Studio/yeomanPOC/blob/main/open.yaml
